### ISSUE TITLE
loadingBackgroundColor not working if isFullscreen is false

### ISSUE THREAD

**Issue by Geoffrey63** [Purchasely/Purchasely-ReactNative#126]
Hello, 

On SDK version 4.4.0, when the `isFullscreen`is set to `false`, the  `loadingBackgroundColor` is not taken into account. 

```      
const result = await Purchasely.presentPresentationForPlacement({
        placementVendorId: 'steps',
        isFullscreen: false,
        loadingBackgroundColor: '#FFFFFFFF',
      });
```

Here is the screenshot taken during the animation : 
![purchasely](https://github.com/Purchasely/Purchasely-ReactNative/assets/1381553/c25ec122-d7b7-4bdd-84e1-64f1cd476fef)

In addition, the close button now have a blue tint. This was not the case in version 4.3.3.

**Comment by EPIKorial** [comment]
Hello @Geoffrey63 ,

Thank you for bringing this issue to our attention.

We are actively investigating the matter and will provide you with an update as soon as we have more information.

We appreciate your feedback and the details you’ve shared. Your input is invaluable in helping us enhance our product.

Best regards,

Florian

**Comment by EPIKorial** [comment]
Hello @Geoffrey63,

Regarding the close button issue, thanks to your feedback, we have fixed the problem. The solution will be included in our next version, which should be released soon.

As for the background color not being applied when using a modal, this issue seems to affect only our React Native bridge. Unfortunately, we don't have a fix for this at the moment. We are working to resolve it as soon as possible. In the meantime, I have a few suggestions:

1. This bug only affects modals, not fullscreen views. Did you consider setting `isFullscreen: true` ? This should resolve both issues right away
2. Have you tried pre-fetching the paywall before presenting it ? Since the issue appears to be related to loading time, a pre-fetched controller shouldn't be affected and should display instantaneously. For more information, please see our documentation on the pre-fetching mechanism: [Pre-Fetching Documentation](https://start.purchasely.com/docs/pre-fetching).

I hope this helps.

Please don't hesitate to reach out if you have any other problems or notice any unexpected behavior.

Best regards,

Florian

**Comment by Geoffrey63** [comment]
Hi @EPIKorial, 

Thank you for the close button fix 💪🏻
Regarding the background, I will look at the pre-fetching doc as you suggested. 

Have a nice day.
