### ISSUE TITLE
Purchasely.userLogin() promise doesn't return anything on Android 

### ISSUE THREAD

**Issue by Geoffrey63** [Purchasely/Purchasely-ReactNative#60]
Hello, 

To make sure we don't have any anonymous users, we use the `Purchasely.userLogin` promise like this : 

```typescript
 Purchasely.userLogin(userPayload.sub)
    .then(_ => {
      setupUserAccount()
        .then(userAccount => {
          Purchasely.onProcessAction(true);
        })
        .catch(onUserInfoError);
    })
    .catch(onUserInfoError);
```

This code works fine on iOS but on Android the promise doesn't return anything and purchase button is stuck in loading state. 
Note that I've checked that `userPayload.sub` is not null. 

Do you have any idea of what can cause this issue ? 

(Tested with React Native SDK version 2.6.8 and 2.7.3)

**Comment by kherembourg** [comment]
Hello @Geoffrey63 

The callback on `userLogin` will not be called on Android if the user id you provide is the same one as already registered by Purchasely. I think you are setting the same user id (null or not) which is why you don't have a callback
But you do not need to wait for it as it is only useful for you when you must refresh your user entitlements, so it is only useful for your method `setupUserAccount()`
`Purchasely.onProcessAction(true);` should be called all the time, like this

```javascript
Purchasely.userLogin(userPayload.sub)
    .then(_ => {
      setupUserAccount()
        .catch(onUserInfoError);
    })
    .catch(onUserInfoError);
    
Purchasely.onProcessAction(true);
```
