### ISSUE TITLE
Last version not published/pinned on Android

### ISSUE THREAD

**Issue by Minishlink** [Purchasely/Purchasely-ReactNative#93]
Hello, 

FYI in the last version there is a warning on Android although the play store package v4.2.4 [does not exist yet](https://mvnrepository.com/artifact/io.purchasely/google-play) (neither core).

`Your dependency for GOOGLE_PLAY_STORE is not up to date, your current version is 42300, please update to version 4.2.4 {"error": [Error: Your dependency for GOOGLE_PLAY_STORE is not up to date, your current version is 42300, please update to version 4.2.4]}`

**Comment by kherembourg** [comment]
Hello @Minishlink 

This is weird, our React Native SDK include our Android SDK 4.2.3 so you should not have this error
4.2.4 is available since yesterday but it takes 24 hours to be referenced on mvnrepository.com

Anyway, you should not have this error as we do not include this version in our React Native SDK for now
Do you include native Purchasely Android SDK in your `build.gradle` file directly? 
Like this `implementation 'io.purchasely:core:4.2.4'` ?

**Comment by Minishlink** [comment]
Shouldn't this be 4.2.4? https://github.com/Purchasely/Purchasely-ReactNative/blob/main/purchasely-android-player/android/build.gradle#L137C3-L137C46 here too https://github.com/Purchasely/Purchasely-ReactNative/blob/main/purchasely-google/android/build.gradle#L132

**Comment by kherembourg** [comment]
No we released 4.2.4 on RN before Android to include a important fix for iOS
You can look at the corresponding table here: https://github.com/Purchasely/Purchasely-ReactNative/blob/main/VERSIONS.md

That's why I don't understand how you get this error, the only to have it is if you include the android sdk yourself in your build.gradle file

**Comment by Minishlink** [comment]
We do have `implementation 'io.purchasely:player:4.2.3'` in build.gradle as it was referenced in one of your docs. Not about `core` though.
But since it works with android version 4.2.3, why would it show a warning?

**Comment by kherembourg** [comment]
Hello @Minishlink 
Sorry forgot to reply

You do not need this native dependency anymore, you can just use the RN dependency for the player directly

This warning is shown to make sure you have everything up to date as there may be a change of class between versions so you always need to have all your versions at the same number
However here I don't understand why you have this warning if you use version 2.4.3 for all dependencies, you must have a 2.4.4 somewhere

**Comment by Minishlink** [comment]
Ok, thanks, I'll stay on 4.2.3 for now anyway, I'll look into it on our next store release

**Comment by Minishlink** [comment]
@kherembourg FYI when removing the dependency in our build.gradle, videos aren't working anymore in Purchasely presentation `implementation 'io.purchasely:player:4.2.3'`

**Comment by kherembourg** [comment]
@Minishlink That's because you need to use our RN dependency for the android player: https://github.com/Purchasely/Purchasely-ReactNative/tree/main/purchasely-android-player

**Comment by Minishlink** [comment]
Yes we do have it

**Comment by kherembourg** [comment]
Yes you're right, we should add it to our Readme too. It has been added in our [documentation](https://docs.purchasely.com/quick-start-1/sdk-installation/react-native-sdk#android-video-player)

I do not advise however to add the dependency in your gradle file, it is too complicate to follow up with the version of the RN SDK, you risk a compilation error or worse a crash.
Using our Android video player SDK for RN is the way to go, inside there is the gradle dependency that we keep up to date
There may be some unnecessary sample functions that came by default, we will remove them
